version: "3.8"
services:
  frontend:
    image: frontend
    restart: always
  backend:
    image: backend
    restart: always
  website:
    image: nginx:alpine
    restart: always
    links:
      - frontend
      - backend
    ports:
      - 80:80
    volumes:
      - ./nginx/confs:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
